config/routes.rb
Rails.application.routes.draw do
  root "users#new"

  resources :sessions,only: [:new , :create, :destroy]
  get "/sessions/:id", to: "sessions#destroy"

  resources :users
  resources :posts ,only: [:new ,:show , :update , :confirm, :edit, :index, :create, :destroy] do
  get "/post/:id", to: "post#destroy"
    collection do
      post :confirm
    end
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user,class_name: 'User',foreign_key: 'user_id'
  validates :content, presence: true
  validates :image, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts
  validates :name, presence: true
  validates :email, uniqueness: true
  validates_format_of :email, with: /@/
  has_secure_password
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  include SessionsHelper
  include PostsHelper

  helper_method :logged_in?, :current_user

  def authenticate_user
    if @current_user == nil
      flash[ :notice ]= t('notice.login_needed')
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?

  def index
    @users=User.all
    @post = Post.new
    @posts = Post.all
  end

  def show
  end

  def edit
  end

  def new
    if params[:back]
      @post = Post.new(post_params)
    else
      @post = Post.new
    end
  end


  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm
    @post = current_user.posts.build(post_params)
    @post.id = params[:id]
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content , :id, :image, :image_cache, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    flash[:danger] = ''
    if logged_in?
      redirect_to posts_path
    end
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'failed to login'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[ :notice ]= ' logged out '
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [ :show , :edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
    @post = @user.posts.build
  end

  def index
    @users = User.all
  end

  def new
    if logged_in?
      redirect_to posts_path
    end

    @user = User.new
  end


  def edit
  end


  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html {redirect_to new_session_path ,notice: "Your account has been successfully created"}
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit( :name, :email, :password , :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper



def isit_me?(post_user)
  post_user == current_user
end
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authenticated_user?
      current_user == @post.user
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

    def logged_in?
      current_user.present?
    end
  end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(current_user)
    gravatar_id = Digest::MD5.hexdigest(current_user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: current_user.name, class: 'gravatar')
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/views/layouts/_header.html.erb

  <header class="header-info" id= "header-display">
    <%= link_to root_path do %><h1><strong>Facebooky</strong></h1><% end %>
    <svg   width="300px" >

    <div id="header-icons" class="text-right">
      
    <% if logged_in? %>
      <span><%= current_user.email %></span><i class="fas fa-user"></i>
      <%= link_to 'Profile', user_path(current_user.id), :class => 'navbar-link' %> |
      <i class="fas fa-home"></i>    <%= link_to 'Home', root_path, :class => 'navbar-link' %> |
      <i class="fas fa-users"></i>    <%= link_to 'Users', users_path, :class => 'navbar-link' %>  |
      <i class="far fa-dot-circle"></i>    <%= link_to 'Notifications', users_path, :class => 'navbar-link' %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete, class: 'navbar-link'  %>

    <% end %>


    </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook CLone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <%= display_meta_tags site: 'Instagram • Capture, edit & share photos, videos & messages with friends & family.',
                        keywords: %w[udemy instagram clone],
                        description: "Create an account or log in to Instagram - A simple, fun & creative way to capture, edit & share photos, videos & messages with friends & family."%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <%= favicon_link_tag 'icon.png' %>


  </head>

  <body>

      <header>
        <%= render 'layouts/header' %>
      </header>

      <%= yield %>


<br>
<br>
<br>
<br>
</body>
</html>


    <!-- <footer class="footer clearfix">
      <strong>Facebook Clone</strong> by <a href="https://github.com/Aminemba/The-Face.git">Amine Lh</a>. One Step at a Time ...
         <a href="https://diver.diveintocode.jp">Join us on Diver </a>.
    </footer> -->

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true ,url: choose_new_or_edit ) do |f| %>

<% if post.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
  <ul>
    <% post.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <li><%= message %></li>
    </div>
    <% end %>
  </ul>
</div>
<% end %>


<div class="field">
  <%= f.text_area :content, placeholder: "What are you thinking..." %>
  <%= f.hidden_field :id   %>

</div>

<div class="field ">
  <%= f.label :image %>
  <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
  <%= f.hidden_field :user_id ,value: current_user.id  %>
  <br>
</div>

<div class="text-center ">
  <%= f.submit "Publish", class: "btn btn-primary btn-publish" %>
  <% end %>
</div>

app/views/posts/confirm.html.erb
<h2> <strong>Confirmation Page</strong> </h2>

<%= form_with(model: @post, local: true) do |form| %>
<div class="text-center">
<div class="field">
<%= form.label :Your_post %>
<h5><%= form.hidden_field :content , class: "field"%></h5>
</div>

<%= form.hidden_field :image %>
<p>Post:<%= @post.content %></p>
<%= image_tag(@post.image.url) if @post.image && @post.image.url %>
<%= form.hidden_field :image_cache %>
<%= form.hidden_field :user_id %>
<%= form.hidden_field :id %>
</div>

<div class="text-center">
<br>
<br>
<%= form.submit "submit" , class: "btn btn-primary"%>
<%= form.submit "back", name:'back' , class: "btn" %>
</div>

<% end %>

app/views/posts/edit.html.erb
<div class="text-center">

  <h4> <strong>Edit your Post</strong></h4>

  <% if current_user.id != @post.user_id %>
   <% controller.redirect_to posts_path %>
  <%end%>

  <%= render 'form', post: @post %>

  <%= link_to 'Show', @post %> |
  <%= link_to 'Back', posts_path %>

</div>

app/views/posts/index.html.erb
<div class="text-center ">
  <h1 id="header-timeline"> <strong>Timeline</strong></h1>

<span><%= link_to 'New Post', new_post_path , class: "btn btn-primary" %></span>



<div class="header_container-menu">
<p id="notice"><%= notice %></p>
<% @posts.each do |post| %>
<article class="post">
  <p class="content">
    <% @users.each do |user| %>
    <% if user.id == post.user_id %>
    <strong><strong><%=user.name%></strong></strong>
    <%end%>

    <%end%>
  </p>
  <br>
  <p><%= post.content %></p>

    <%= image_tag post.image.url,class: "post-image" %>
  <br>

    <small><%= post.created_at.strftime('%Y/%-m/%-d %-H:%-M') %>
    </small>
  <br>

  <span><%= link_to 'Show', post , class: 'btn btn-primary' %></span>
    <% if current_user.id == post.user_id %>
  <span><%= link_to 'Edit', edit_post_path(post) , class: 'btn btn-primary' %></span>
  <span><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' },  class: 'btn btn-primary' %></span>
     <%end%>
</article>
<% end %>
</div>
</div>

app/views/posts/new.html.erb
<h2><strong>New Post</strong></h2>

<div class=" text-center ">
  <%= render 'form', post: @post %>
  <%= link_to 'Back', posts_path , class: "btn " %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center">
  <h2><strong>Your post</strong></h2>

  <p><%= @post.content %></p>

  <br>
  <p><strong>Image:</strong> </p>
    <%= image_tag @post.image.url,class: "post-image"  %>
  <% if current_user.id == @post.user_id %>
  <%= link_to 'Edit', edit_post_path(@post) , class: "btn btn-primary"%>
  <%end%>

  <%= link_to 'Back', posts_path , class: "btn btn-primary"%>

</div>

app/views/users/_form.html.erb
<h1> users/form </h1>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<div class="text-center">
<%= link_to 'Back', new_user_path , class: "btn btn-primary" %>  
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
 <ul class="alert alert-danger" role="alert">
   <% @user.errors.full_messages.each do |message| %>
     <li><%= message %></li>
   <% end %>
 </ul>
 <% end %>
<div class="text-center">
<h2> <strong>Sign up</strong> </h2>

<%= form_with(model: @user, local: true) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "password-confirmation" %>
  </div>
<br/>
  <div class="actions">
    <%= f.submit "Create my account " %>
  </div>


<% end %>

</div>

  <div class="text-center">
    <%= link_to "Login", new_session_path,class:"navbar-link"  %>
  </div>

app/views/users/show.html.erb
<div class="text-center">
  <h1> Welcome to your Profile , <strong><%= @user.name %></strong> </h1>
  <p> <strong>User email:</strong> <%= @user.email %></p>
<br>
 <h3> <strong>My Activity</strong></h3>
  <% @posts.each do |post| %>
  <section>
    <p class="created_at"><%= post.created_at.strftime('%Y/%-m/%-d %-H:%-M') %></p>
    <p><%= post.content %></p>
    <%= image_tag post.image.url ,class: "post-image" %>
    <%= link_to posts_path %>
  </section>
  <% end %>
</div>